require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
platform :ios, '10.2'



target 'Elsahel' do
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])

  target 'ElsahelTests' do
    inherit! :complete
    # Pods for testing
  end

  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'

  use_native_modules!

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!({ 'Flipper' => '0.74.0' })
  post_install do |installer|
    flipper_post_install(installer)
  end
end

target 'Elsahel-tvOS' do
  # Pods for Elsahel-tvOS

  target 'Elsahel-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end
end